apiVersion : apps/v1
kind: Deployment
metadata:
  name: eunyungpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eunyungpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: eunyungpipelinesjavascriptdocker 
    spec:
      containers:
        - name: eunyungpipelinesjavascriptdocker 
          image: 0429testcontainerregistry.azurecr.io/eunyungpipelinesjavascriptdocker
          ports:
          - containerPort: 8080