apiVersion : apps/v1
kind: Deployment
metadata:
  name: eunyung0429testjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eunyung0429testjavascriptdocker
  template:
    metadata:
      labels:
        app: eunyung0429testjavascriptdocker 
    spec:
      containers:
        - name: eunyung0429testjavascriptdocker 
          image: 0429test2containerregistry.azurecr.io/0429testjavascriptdocker
          ports:
          - containerPort: 8080
