apiVersion: v1
kind: Service
metadata:
    name: eunyung0429testjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: 0429testjavascriptdocker
